### ISSUE TITLE
The feature descriptions from a gb file produced by snapgene_file_to_seq_record() lack the last character

### ISSUE THREAD

**Issue by nicolazilio** [IsaacLuo/SnapGeneFileReader#2]
Great library for working with SnapGene files, however when I try to convert a SnapGene file to genebank with snapgene_file_to_seq_record(), like so:

```
seqObject = snapgene_file_to_seq_record(my_snapgene_file)
for i in seqObject.features:
    print i
```

I get, for example:

```
type: CDS
location: [1749:1769](+)
id: SV40 NLS
qualifiers:
    Key: codon_start, Value:
    Key: locus_tag, Value:
    Key: note, Value:
    Key: product, Value: nuclear localization signal of SV40 large T antige
    Key: protein_id, Value:
    Key: transl_table, Value:
    Key: translation, Value: PKKKRK

type: CDS
location: [1725:1745](+)
id: SV40 NLS
qualifiers:
    Key: codon_start, Value:
    Key: locus_tag, Value:
    Key: note, Value:
    Key: product, Value: nuclear localization signal of SV40 large T antige
    Key: protein_id, Value:
    Key: transl_table, Value:
    Key: translation, Value: PKKKRK

type: CDS
location: [1701:1721](+)
id: SV40 NLS
qualifiers:
    Key: codon_start, Value:
    Key: locus_tag, Value:
    Key: note, Value:
    Key: product, Value: nuclear localization signal of SV40 large T antige
    Key: protein_id, Value:
    Key: transl_table, Value:
    Key: translation, Value: PKKKRK

type: CDS
location: [1818:2518](+)
id: mCherry
qualifiers:
    Key: codon_start, Value:
    Key: note, Value: mammalian codon-optimize
    Key: product, Value: monomeric derivative of DsRed fluorescent protein (Shaner et al., 2004
    Key: transl_table, Value:
    Key: translation, Value: MVSKGEEDNMAIIKEFMRFKVHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSPQFMYGSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLRGTNFPSDGPVMQKKTMGWEASSERMYPEDGALKGEIKQRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNVNIKLDITSHNEDYTIVEQYERAEGRHSTGGMD

type: protein_bind
location: [4467:4483](?)
id: lac operator
qualifiers:
    Key: bound_moiety, Value: lac repressor encoded by lac
    Key: note, Value: The lac repressor binds to the lac operator to inhibit transcription in E. coli. This inhibition can be relieved by adding lactose or isopropyl-β-D-thiogalactopyranoside (IPTG)
```
